/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoleksiyonSlugRouteImport } from './routes/koleksiyon.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoleksiyonSlugRoute = KoleksiyonSlugRouteImport.update({
  id: '/koleksiyon/$slug',
  path: '/koleksiyon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/koleksiyon/$slug': typeof KoleksiyonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/koleksiyon/$slug': typeof KoleksiyonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/koleksiyon/$slug': typeof KoleksiyonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/koleksiyon/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/koleksiyon/$slug'
  id: '__root__' | '/' | '/koleksiyon/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KoleksiyonSlugRoute: typeof KoleksiyonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koleksiyon/$slug': {
      id: '/koleksiyon/$slug'
      path: '/koleksiyon/$slug'
      fullPath: '/koleksiyon/$slug'
      preLoaderRoute: typeof KoleksiyonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KoleksiyonSlugRoute: KoleksiyonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
