/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRoomComposeRouteImport } from './routes/api/room-compose'
import { Route as ApiSpinFrameRouteImport } from './routes/api/spin-frame'
import { Route as KoleksiyonSlugRouteImport } from './routes/koleksiyon.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomComposeRoute = ApiRoomComposeRouteImport.update({
  id: '/api/room-compose',
  path: '/api/room-compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpinFrameRoute = ApiSpinFrameRouteImport.update({
  id: '/api/spin-frame',
  path: '/api/spin-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const KoleksiyonSlugRoute = KoleksiyonSlugRouteImport.update({
  id: '/koleksiyon/$slug',
  path: '/koleksiyon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/room-compose': typeof ApiRoomComposeRoute
  '/api/spin-frame': typeof ApiSpinFrameRoute
  '/koleksiyon/$slug': typeof KoleksiyonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/room-compose': typeof ApiRoomComposeRoute
  '/api/spin-frame': typeof ApiSpinFrameRoute
  '/koleksiyon/$slug': typeof KoleksiyonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/room-compose': typeof ApiRoomComposeRoute
  '/api/spin-frame': typeof ApiSpinFrameRoute
  '/koleksiyon/$slug': typeof KoleksiyonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/room-compose' | '/api/spin-frame' | '/koleksiyon/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/room-compose' | '/api/spin-frame' | '/koleksiyon/$slug'
  id:
    | '__root__'
    | '/'
    | '/api/room-compose'
    | '/api/spin-frame'
    | '/koleksiyon/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoomComposeRoute: typeof ApiRoomComposeRoute
  ApiSpinFrameRoute: typeof ApiSpinFrameRoute
  KoleksiyonSlugRoute: typeof KoleksiyonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/room-compose': {
      id: '/api/room-compose'
      path: '/api/room-compose'
      fullPath: '/api/room-compose'
      preLoaderRoute: typeof ApiRoomComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spin-frame': {
      id: '/api/spin-frame'
      path: '/api/spin-frame'
      fullPath: '/api/spin-frame'
      preLoaderRoute: typeof ApiSpinFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koleksiyon/$slug': {
      id: '/koleksiyon/$slug'
      path: '/koleksiyon/$slug'
      fullPath: '/koleksiyon/$slug'
      preLoaderRoute: typeof KoleksiyonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoomComposeRoute: ApiRoomComposeRoute,
  ApiSpinFrameRoute: ApiSpinFrameRoute,
  KoleksiyonSlugRoute: KoleksiyonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
